spring.application.name=backend
server.address=127.0.0.1
server.port=8721
management.endpoints.web.exposure.include=health

webrtc.ice-servers[0].urls=stun:cooler-test.duckdns.org:3478
webrtc.ice-servers[1].urls=turn:cooler-test.duckdns.org:3478
webrtc.ice-servers[1].username=webrtc
webrtc.ice-servers[1].credential=changeme
